# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV["DB_HOST"]%>
  username: principia
  password: <%= ENV["DB_PASS"]%>
  database: principia_dev

test:
  <<: *default
  database: principia_test
  username: principia
  password: <%= ENV["DB_PASS"]%>
  database: principia_test

production:
  <<: *default
  database: principia_production
